docs:
- changed-files:
  - any-glob-to-any-file: '**/*.md'

action:
- changed-files:
  - any-glob-to-any-file: '.github/action/*'

lib:
- changed-files:
  - any-glob-to-any-file:
    - 'src/'

cli:
- changed-files:
  - any-glob-to-any-file:
    - 'geekorm-cli/'

lib-core:
- changed-files:
  - any-glob-to-any-file:
    - 'geekorm-core/'

lib-derive:
- changed-files:
  - any-glob-to-any-file:
    - 'geekorm-derive/'

examples:
- changed-files:
  - any-glob-to-any-file:
    - 'examples/'

