name: "geekorm"
repository: "42ByteLabs/geekorm"
version: 0.8.1

locations:
  - name: "Cargo - Workmembers"
    paths:
      - "Cargo.toml"
      - "**/Cargo.toml"
    patterns:
      - 'geekorm = \{.*version\s*=\s*"\^{version}".*\}'
      - 'geekorm-core = \{.*version\s*=\s*"\^{version}".*\}'
      - 'geekorm-derive = \{.*version\s*=\s*"\^{version}".*\}'

