name: "geekorm"
repository: "42ByteLabs/geekorm"
version: 0.11.4

ecosystems:
  - Docs
  - Cargo

locations:
  - name: "Cargo - Workmembers"
    paths:
      - "Cargo.toml"
      - "**/Cargo.toml"
    patterns:
      - 'geekorm = \{.*version\s*=\s*"\^{version}".*\}'
      - 'geekorm-core = \{.*version\s*=\s*"\^{version}".*\}'
      - 'geekorm-derive = \{.*version\s*=\s*"\^{version}".*\}'

