[package]
name = "geekorm-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
geekorm-core = { workspace = true, path = "../geekorm-core" }
proc-macro2 = "1.0.79"
quote = "1.0.35"
syn = "2.0.53"
