[package]
name = "geekorm-example-users"
version.workspace = true
license.workspace = true
edition.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
geekorm = { path = "../../" }
