[package]
name = "geekorm-cli"
description = "GeekORM Commmand Line Interface"

version.workspace = true
categories.workspace = true
keywords.workspace = true

documentation.workspace = true
repository.workspace = true

license.workspace = true

edition.workspace = true
rust-version.workspace = true

authors.workspace = true

[dependencies]
anyhow = "1.0"
geekorm = { path = "../", version = "^0.3" }
