[package]
name = "geekorm-core"
version.workspace = true
edition.workspace = true
authors.workspace = true

[features]
default = ["uuid", "chrono"]

uuid = []
chrono = []

# This feature is for testing
backends = ["libsql"]
libsql = ["dep:libsql"]

[dependencies]
thiserror = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
chrono = { version = "0.4" }
libsql = { version = "0.3", optional = true }
log = { version = "0.4.21", features = ["std", "serde"] }


[dev-dependencies]
geekorm = { path = ".." }
