name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    # https://github.com/42ByteLabs/.github/blob/main/.github/workflows/cargo-build.yml
    uses: 42ByteLabs/.github/.github/workflows/cargo.yml@865c36613799988f036ed780621e010ea0bd7750 # v0.14
    secrets: inherit
    permissions:
      contents: read
      actions: read
      security-events: write
    with:
      features: "all"

  cli:
    name: CLI
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GeekORM"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          path: geekorm

      - name: "Checkout GeekORM Migrations"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          repository: 42ByteLabs/geekorm-migrations
          path: geekorm-migrations

      - uses: dtolnay/rust-toolchain@be39649afda95dbf70f87cce95f68b8d5797b296 # nightly
        with:
          toolchain: nightly
          components: clippy,rustfmt

      - name: Restore cached Cargo
        id: cache-restore
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            geekorm/target/
            geekorm-migrations/target/
          key: ${{ runner.os }}-stable-cargo

      - name: Build CLI
        working-directory: ${{ github.workspace }}/geekorm-migrations
        run: |
          cargo install --path ../geekorm/geekorm-cli

          geekorm-cli display

          geekorm-cli test

          cargo run
