name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    # https://github.com/42ByteLabs/.github/blob/main/.github/workflows/dep-review.yml
    uses: 42ByteLabs/.github/.github/workflows/dep-review.yml.yml@main
    secrets: inherit
