name: 'Markdown Lint'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: read

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v7

      - name: "Filter Changes"
        uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706
        id: changes
        with:
          filters: |
            src:
              - '**.md'

      # lint markdown
      - name: "Lint Markdown"
        if: steps.changes.outputs.src == 'true'
        run: |
          npm install -g markdownlint-cli
          markdownlint '**.md' --ignore node_modules --disable MD013
