name: "Release"

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  cargo-publish:
    # https://github.com/42ByteLabs/.github/blob/main/.github/workflows/cargo-publish.yml
    uses: 42ByteLabs/.github/.github/workflows/cargo-publish.yml@v0.4
    secrets: inherit
    with:
      crate: geekorm
