name: "Release"

on:
  push:
    branches:
      - "main"

jobs:
  cargo-publish:
    # https://github.com/42ByteLabs/.github/blob/main/.github/workflows/cargo-publish.yml
    uses: 42ByteLabs/.github/.github/workflows/cargo-publish.yml@crates-check
    secrets: inherit
    with:
      crate: geekorm
