name: "Release Train"

on:
  # every week on Wednesday at 14:00
  schedule:
    - cron: "0 14 * * 3"
  # Manual
  workflow_dispatch:

jobs:
  train:
    # https://github.com/42ByteLabs/.github/blob/main/.github/workflows/cargo-train.yml
    uses: 42ByteLabs/.github/.github/workflows/cargo-train.yml@v0.6
    secrets: inherit
    with:
      crate: geekorm
