name: Semgrep

on:
  push:
    branches: ["main"]
  pull_request: {}
  workflow_dispatch: {}
  schedule:
    - cron: '0 14 * * 2'

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    if: (github.actor != 'dependabot[bot]')

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Run Semgrep"
        run: semgrep . --sarif --metrics=off --output semgrep.sarif
        env:
          SEMGREP_RULES: p/default

      - name: "Upload SARIF file"
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
        if: always()
